apiVersion: v1
kind: Service
metadata:
  name: clixx-app-service
  namespace: clixx
spec:
  # ClusterIP only.traffic comes in through the Ingress/ALB
  type: ClusterIP
  selector:
    app: clixx-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80